[package]
name = "its-rs"
version = "0.1.7"
edition = "2024"
description = "Rust implementation of Impo Time System - 147 days in year, consistent day count in month, 0:00 starts in Novosibirsk's earliest night in 50-year span in history"
license = "MIT"
repository = "https://github.com/ImpostorBoy228/ITS"
# readme = "README.md"
keywords = ["time", "time systems", "ImpostorBoy", "impo ecosystem"]
categories = ["date-and-time"]

[dependencies]
